config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root  "product#index"

  post 'product', to: 'product#add_cart'

  get 'bill', to: 'bill#show' # /bill
  post 'bill', to: 'bill#create'

  get 'history_bills', to: 'bill#show_history'
  get "/history_bills/:id", to: "bill#showbilldetails"
  
  get 'cart', to: 'cart#show', as: 'cart'
  post 'cart', to: 'cart#add', as: 'add_to_cart'
  patch 'cart/:product_id', to: 'cart#edit_quantity', as: 'edit_quantity_cart'
  delete 'cart/:product_id', to: 'cart#delete', as: 'delete_product_cart'

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @cart = cookies[:cart].present? ? JSON.parse(cookies[:cart]) : []
    begin
      @total_price = @cart.sum { |item| Product.find(item["product_id"]).price * item["quantity"] }
    rescue
      cookies[:cart] = []
      redirect_to root_path
    end
   
  end
  
  

  def add
    product = Product.find(params[:product_id])

    if cookies[:cart].present?
      cart = JSON.parse(cookies[:cart])
    else
      cart = []
    end

    existing_item = cart.find { |item| item["product_id"] == product.id }

    if existing_item.present?
      existing_item["quantity"] += 1
    else
      cart << { "product_id" => product.id, "quantity" => 1 }
    end

    cookies[:cart] = cart.to_json

    redirect_to cart_path
  end
  
  def delete
    product = Product.find(params[:product_id])
    cart = JSON.parse(cookies[:cart])
    cart.delete_if { |item| item["product_id"] == product.id }
    cookies[:cart] = cart.to_json

    redirect_to cart_path
  end
  
  def edit_quantity
    product = Product.find(params[:product_id])
    cart = JSON.parse(cookies[:cart])
    item = cart.find { |i| i["product_id"] == product.id }
    item["quantity"] = params[:quantity].to_i
    cookies[:cart] = cart.to_json

    redirect_to cart_path
  end


#   def show
#     @cart = cart_items
#     @products = Product.find(@cart.keys)
#   end
  
#   private

#   def cart_items
#     return {} if cookies[:cart].nil?

#     JSON.parse(cookies[:cart]).transform_keys(&:to_i)
#   end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/cart/show.html.erb
<div class="container mt-4">
<h1 class="font-weight-bold">あなたのカート</h1>

<table>
  <thead>
    <tr>
        <th>番号順</th>
      <th>製品</th>
      <th>量</th>
      <th>価格</th>
      <th>合計</th>
      <th>行動</th>
  </tr>
  </thead>
  <tbody>
  <% @cart.each_with_index do |item, index| %>
    <tr>
        <% product = Product.find(item["product_id"]) %>
        <td><%= (index + 1) %></td>
        <td><%= product.product_name %></td>
      <td>
        <%= form_tag(edit_quantity_cart_path(product), method: :patch) do %>
          <%= number_field_tag :quantity, item["quantity"], size: 2 %>
          <%= submit_tag "アップデート", class: "btn btn-secondary" %>
        <% end %>
      </td>
      <td><%= number_to_currency(product.price) %></td>
      <td><%= number_to_currency(item["quantity"] * product.price) %></td>
      <td><%= link_to "消去", delete_product_cart_path(product), class: "btn btn-danger", method: :delete %></td>
    </tr>
  <% end %>
  <tr>
    <td colspan="4">合計:</td>
    <td><%= number_to_currency(@total_price) %></td>
  </tr>
  </tbody>
</table>
<%= link_to "チェックアウト", bill_path, class: "mt-3 btn btn-primary" %>
</div>

<style>
  table {
    width: 100%;
    border-collapse: collapse;
  }

  th, td {
    border: 1px solid #ddd;
    padding: 8px;
    text-align: left;
  }

  th {
    background-color: #ddd;
  }
</style>
