config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root  "product#index"

  post 'product', to: 'product#add_cart'

  get 'bill', to: 'bill#show' # /bill
  post 'bill', to: 'bill#create'

  get 'history_bills', to: 'bill#show_history'
  get "/history_bills/:id", to: "bill#showbilldetails"
  
  get 'cart', to: 'cart#show', as: 'cart'
  post 'cart', to: 'cart#add', as: 'add_to_cart'
  patch 'cart/:product_id', to: 'cart#edit_quantity', as: 'edit_quantity_cart'
  delete 'cart/:product_id', to: 'cart#delete', as: 'delete_product_cart'

end

app/views/partials/_flash_msg.html.erb
<div id="flash">
<% flash.each do |name,msg| %>
  <div class="alert alert-<%= name %>" role="alert">
      <%= msg %> 
  </div>
<%end%>
</div>
<script type="text/javascript">
$(document).ready(function(){
  setTimeout(function(){
    $('#flash').remove();
  }, 5000);
 })
</script>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">グループ６</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">ホーム</a>
        </li>
        <li class="nav-item">
            <a class="nav-link ms-4" href="/cart">カート</a>
        </li>
          <li class="nav-item">
            <a class="nav-link ms-4" href="<%= history_bills_path %>">購入履歴</a>
        </li>
      </ul>

      <span class="navbar-text ms-5">
      <% if user_signed_in? %>
        こんにちは, <%= link_to current_user.name, user_session_path %>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "サインイン", new_user_session_path %>
        <%= link_to "ユーザ登録", new_user_registration_path %>
      <% end %>
      </span>
    </div>
  </div>
</nav>